#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.
ps -eo user,lstart,cmd --sort=start_time | awk 'NR==1{$2="STARTED"; print $1, $2, $NF} NR>1{$6=strftime("%H:%M:%S", mktime($2" "$3" "$4" "$5" "$6" "$7)); print $1, $6, $NF}'
